import { describe, it, expect } from 'vitest'
import { solvePart1, solvePart2 } from './solve'

const exampleInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

describe('Day 7: Laboratories', () => {
  describe('Part 1', () => {
    it('should count beam splits correctly in example', () => {
      const result = solvePart1(exampleInput)
      expect(result).toBe(21)
    })
  })

  describe('Part 2', () => {
    it('should count unique timelines correctly in example', () => {
      const result = solvePart2(exampleInput)
      expect(result).toBe(40)
    })
  })
})
